

static const char text[] =
                "dcl_position v0\n"
                "dcl_normal v1\n"
                "dcl_texcoord v2\n"
                "dcl_blendindices v3\n"
                "dcl_blendweight v4\n"
                "mad r0, v3, c90.x, c90.y\n"
                "mov a0.x, r0.x\n"
                "mul r1, v4.x, c0[a0.x]\n"
                "mul r2, v4.x, c1[a0.x]\n"
                "mul r3, v4.x, c2[a0.x]\n"
                "mov a0.x, r0.y\n"
                "mad r1, v4.y, c0[a0.x], r1\n"
                "mad r2, v4.y, c1[a0.x], r2\n"
                "mad r3, v4.y, c2[a0.x], r3\n"
                "mov a0.x, r0.z\n"
                "mad r1, v4.z, c0[a0.x], r1\n"
                "mad r2, v4.z, c1[a0.x], r2\n"
                "mad r3, v4.z, c2[a0.x], r3\n"
                "mov a0.x, r0.w\n"
                "mad r1, v4.w, c0[a0.x], r1\n"
                "mad r2, v4.w, c1[a0.x], r2\n"
                "mad r3, v4.w, c2[a0.x], r3\n"
                "dp4 r4.x, v0, r1\n"
                "dp4 r4.y, v0, r2\n"
                "dp4 r4.z, v0, r3\n"
                "mov r4.w, c91.z\n"
                "mov r5.xyz, r4\n"
                "mov r5.w, c91.z\n"
                "dp4 oPos.x, r5, c0\n"
                "dp4 oPos.y, r5, c1\n"
                "dp4 oPos.z, r5, c2\n"
                "dp4 oPos.w, r5, c3\n"
                "mov oT0, v2\n";
