

static const char text[] =
                "dcl_position v0\n"
                "dcl_normal v1\n"
                "dcl_texcoord v2\n"
                "dcl_blendindices v3\n"
                "dcl_blendweight v4\n"
                "mad r0, v3, c90.x, c90.y\n"
                "mov a0.x, r0.x\n"
                "mul r1, v4.x, c0[a0.x]\n"
                "mul r2, v4.x, c1[a0.x]\n"
                "mul r3, v4.x, c2[a0.x]\n"
                "mov a0.x, r0.y\n"
                "mad r1, v4.y, c0[a0.x], r1\n"
                "mad r2, v4.y, c1[a0.x], r2\n"
                "mad r3, v4.y, c2[a0.x], r3\n"
                "mov a0.x, r0.z\n"
                "mad r1, v4.z, c0[a0.x], r1\n"
                "mad r2, v4.z, c1[a0.x], r2\n"
                "mad r3, v4.z, c2[a0.x], r3\n"
                "mov a0.x, r0.w\n"
                "mad r1, v4.w, c0[a0.x], r1\n"
                "mad r2, v4.w, c1[a0.x], r2\n"
                "mad r3, v4.w, c2[a0.x], r3\n"
                "dp4 r4.x, v0, r1\n"
                "dp4 r4.y, v0, r2\n"
                "dp4 r4.z, v0, r3\n"
                "dp3 r5.x, v1, r1\n"
                "dp3 r5.y, v1, r2\n"
                "dp3 r5.z, v1, r3\n"
                "dp3 r6.w, r5.xyzz, r5.xyzz\n"
                "rsq r6.w, r6.w\n"
                "mul r5.xyz, r5.xyzz, r6.w\n"
                "mov r4.w, c91.z\n"
                "mov r7.xyz, r4\n"
                "mov r7.w, c91.z\n"
                "dp4 oPos.x, r7, c0\n"
                "dp4 oPos.y, r7, c1\n"
                "dp4 oPos.z, r7, c2\n"
                "dp4 oPos.w, r7, c3\n"
                "dp3 r8.w, r5, c6\n"
                "max r8.w, r8.w, c91.x\n"
                "min r8.w, r8.w, c91.z\n"
                "mul r9, c7, r8.w\n"
                "add oD0, r9, c8\n";
